# Generated by Django 5.2 on 2025-04-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.CharField(
                default="lead", max_length=20, verbose_name="Статус"
            ),
        ),
    ]
